### ISSUE TITLE
Excess Code in Code Along

### ISSUE THREAD

**Issue by sbs1997** [learn-co-curriculum/react-hooks-react-router-code-along#13]
### Canvas Link

https://learning.flatironschool.com/courses/6808/pages/react-router-code-along?module_item_id=594496

### Concern

The example text for the NavLinks section has an entire unused App Component that never gets called.

### Suggested Changes

Either delete it or use it in the ReactDOM.render() function

**Comment by lizbur10** [comment]
Hi @sbs1997 ! Thanks for bringing this to our attention! This lesson has been updated and the issue has been resolved 💙
