### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by holmes-software** [learn-co-curriculum/react-hooks-react-router-code-along#5]
### Canvas Link

https://learning.flatironschool.com/courses/4550/assignments/157598?module_item_id=335803

### Concern

The "Compose with" link that goes to the below address is broken. The webpage does not seem to exist.
https://reactgraphql.academy/react/react-is-all-about-composition-react-hooks-render-props-hocs/

### Additional Context

![image](https://user-images.githubusercontent.com/91363480/143274872-0c72a0e8-d140-44d2-aae1-8954efb2da12.png)

**Comment by ihollander** [comment]
Thanks @CitrusRaspberry! We'll replace the broken link with relevant material.
