### ISSUE TITLE
Failed to compile error when pasting code from the code along

### ISSUE THREAD

**Issue by angelroundtrip** [learn-co-curriculum/react-hooks-react-router-code-along#7]
### Canvas Link

https://learning.flatironschool.com/courses/4986/assignments/165744

### Concern

import React from "react";
import ReactDOM from "react-dom";
import { BrowserRouter } from "react-router-dom";
import App from "./components/App";

ReactDOM.render(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById("root")
);

### Additional Context

I got a failed to compile error when pasting code on the refactoring portion of the lesson due to import App from "./components/App";

### Suggested Changes

import React from "react";
import ReactDOM from "react-dom";
import { BrowserRouter } from "react-router-dom";
import App from "./App";

ReactDOM.render(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById("root")
);

**Comment by graciemcguire** [comment]
Hi @angelroundtrip, thanks for raising this issue! 
In the `Refactoring` section of the Code Along (starts on line 455 of the README), we break all the components into their own files and add to the new components folder for organization. While it isn't required to do this for all of your App component as well, we strongly suggest it for the sake of organization.
I'm going to close this issue for now, but if you think I have closed this in error please feel free to reopen it or raise another issue. 
Thanks again, and happy coding!
